### ISSUE TITLE
CAM009 Rupert x1: hole in shell

### ISSUE THREAD

**Issue by TomJClark** [CityRC/Equipment#10]
There's a hole in Rupert's bow (or stern, can't quite remember). Easy to see, and looks like it goes the whole way through. With a heavy rower it may be below the water line. 

Cheers
Tom

**Comment by 13enedict** [comment]
Taken Rupert inside to fix the hole. There were a couple of holes and several bits of damage to the paintwork. It's been prepped for filler. I noticed it also needs a new hatch cover.

**Comment by 13enedict** [comment]
OK, I have replaced the damaged hatch cover. I also had a better a look at it while it was the right side up. There is quite a bit to do:

- The deck and upper hull has a number of holes and several pieces of damage that do not penetrate
- The runners are worn and pitted
- The seat wheel bearings are very worn
- The bow ball is damaged
- The bow is damaged
- One shoe is degrading and ripped
- The oarlocks and/or pitch inserts are severely worn

Since almost all parts of the boat are damaged, it is reasonable to assume that this boat has not had proper maintenance for a very long time. For now, it is out of action while it is being repaired.

**Comment by TomJClark** [comment]
Cheers!
agree about the boat - it needs a bit of an overhaul!

Sent from my iPhone

On 23 Nov 2015, at 19:52, Benedict <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I have replaced the damaged hatch cover. I also had a better a look at it while it was the right side up. There is quite a bit to do:

  *   The deck and upper hull has a number of holes and several pieces of damage that do not penetrate
  *   The runners are worn and pitted
  *   The seat wheel bearings are very worn
  *   The bow ball is damaged
  *   The bow is damaged
  *   One shoe is degrading and ripped
  *   The oarlocks and/or pitch inserts are severely worn

Since almost all parts of the boat are damaged, it is reasonable to assume that this boat has not had proper maintenance for a very long time. For now, it is out of action while it is being repaired.

-

**Comment by 13enedict** [comment]
OK, the weather is quite bad which will make sorting out the holes difficult. For now, I have covered the holes in tape and replaced the seat tracks and wheels so it slide smoothly rather than like a roller coaster's chain lift. I have also sorted out the bow.

This means that Rupert can be used again and I'll sort the rest out soon.

**Comment by TomJClark** [comment]
Cheers! With the wind I can't see anyone sculling for a bit!

Tom

Sent from my iPhone

On 30 Nov 2015, at 21:41, Benedict <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, the weather is quite bad which will make sorting out the holes difficult. For now, I have covered the holes in tape and replaced the seat tracks and wheels so it slide smoothly rather than like a roller coaster's chain lift. I have also sorted out the bow.

This means that Rupert can be used again and I'll sort the rest out soon.

-
