### ISSUE TITLE
Redeham & Weep Steering Wire

### ISSUE THREAD

**Issue by colmcmurphy** [CityRC/Equipment#132]
Steering wire snapped during outing on Thursday October 7th. 

No Benedict, is the answer to your question in advance. I wasn't pulling too hard!

**Comment by Jess-upton** [comment]
Can you please let me know status - will Redeham be ok to use on Thursday evening?

**Comment by 13enedict** [comment]
If you can (arrange for the girls to) put it on trestles between City and F&T, I'll do it during the outing tonight. I'll also get some wood put on the rack, if I get time

**Comment by Jess-upton** [comment]
Hi - is there a good time to put this on trestles this weekend to get the wire replaced?
With Wholly needing the bows fixed so that a bowball stays on and the steering on Redeham needing repair Laurie is getting a little more use than I would like.  Happy to repair myself if we have rudder wire - just let me know
Thanks
Jess

**Comment by 13enedict** [comment]
I'm on the water at 10am, so if it can be on tressles at noon, I'll put new wire on. I'm happy to do it, it's quite satisfying but I don't mind if you do either. There's a big reel of wire on the shelf at the back. It's not a big deal but ideally we'd swap the pulleys out as the ones that are on there are the removable ones intended for the rudder end.

**Comment by Jess-upton** [comment]
We will put on Trestles after our 10am outing.
Thank you

**Comment by 13enedict** [comment]
Removed old steering wire and incorrect pulleys and got new pulleys. Jess fitted while I was doing Seb's core / flex tests
