### ISSUE TITLE
Caroline &Joanne stroke rigger screw loose

### ISSUE THREAD

**Issue by DarthSlater** [CityRC/Equipment#256]
C&J stroke rigger the back arm is loose because the thread of the screw is buggered.  Need a new screw and the existing screw will need to be smacked out with a hammer.  Use the force

**Comment by 13enedict** [comment]
I knew they shouldn't have listened to JLA and left it alone 🙄

**Comment by DarthSlater** [comment]
I find your lack of faith.... disturbing....😉

**Comment by NSinclair94** [comment]
What is the background on this?

**Comment by 13enedict** [comment]
The women took the boat out over the weekend and Jade at stroke complained
that she couldn't tap down. They decided that there was a problem with the
boat. Jack LA was around and decided that the problem was the missing
carbon lip bushes so I think they put washers in the gap. It was all
fucking mental - there was nothing wrong with the rigging and it was
probably just a bad outing but I was too tired after sculling myself to get
involved.

**Comment by CCRCJuniors** [comment]
This is by far the best explanation ever!

Brilliant.

Sent from my Phone


Annie Leighton
CCRC Junior Squad Coordinator
Email: ccrcjuniors@gmail.com
Phone: 07707 910 366
City of Cambridge Rowing Club
Website: www.cityrc.co.uk

Availability Link:
https://docs.google.com/spreadsheets/d/1vfo_MfBiIJKfb6-TcMSLMkUHHFuqvas54PWLzbnJdXw/edit#gid=794161339

Race Account:
https://docs.google.com/spreadsheets/d/14qL8zRb4j0erFcsk-xjM3vaPNde9rrUXsrepUfbihmo/edit#gid=625817172
-----------------------------------------------
Registered in England as a Company Limited by Guarantee, Company
Number 09816395

**Comment by DarthSlater** [comment]
A third bad outing and to be fair people  (probably the men) keep messing
with the 'washers' on the gates.

We, like everyone else probably, just need a screw

**Comment by 13enedict** [comment]
Removed the screw in question. The problem was that someone had removed the carbon lip bush nut and then tightened the 10mm rigger nut, crushing the lip bush.
