### ISSUE TITLE
Broken collar on M3 blade

### ISSUE THREAD

**Issue by Terywall** [CityRC/Equipment#273]

**Comment by NSinclair94** [comment]
Could you start looking after the blades? No one else has this problem. Just for reference, they cost 350 pounds each.

I will find a collar and leave it on the bench for you to fit.

**Comment by Terywall** [comment]
The collar wasn't broken on the last outing so it's likely to have happened in a morning outing with the mixed crew.  No idea how and where it had happened but yes, of course we will look after the blades.  The blade costs £350, yes but I'm sure you can replace the collar for a few pounds, no?

**Comment by NSinclair94** [comment]
The replacement collars cost £5 each, plus delivery. For as long as I have been rowing( ~4 years) I have never known these to break. The point I am making is that if they continue to be misused there may be damage that is caused that is greater than £5.
It concerns me that that within the lower mens boats there is little appreciation for how expensive some of the equipment is. There have been a shed load of issues coming from these crews and these are the ones that get reported.
Yesterday I saw you and your crew get doreen out and swinging the stern round and striking tony ( a boat which is due to go to Henley Qualifying in a week), a collision between £33,000 worth of boat, and no one batted an eyelid.
I could roll off another four or five issues without even having to look at the current and closed issues.

**Comment by NSinclair94** [comment]
Collar is hanging on the spanner rack in the workshop
